project:
  title: mb-labs
  type: website
  execute-dir: file
  output-dir: _site
  preview:
    port: 5555

website:
  title: "Mel B. my-blog"
  favicon: assets/mb-square.png
  image: assets/mb-square.png
  twitter-card: false
  open-graph: true
  site-url: https://mbacou.com
  repo-url: https://github.com/mbacou/mb-labs
  repo-branch: quarto
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: false
  description: Playground for consulting and data science projects

  navbar:
    title: Mel B. my-blog
    foreground: dark
    background: transparent
    search: true
    collapse: false
    tools-collapse: false
    toggle-position: right
    tools:
      - icon: github
        href: https://github.com/mbacou/mb-labs
      - icon: telegram
        href: https://t.me/mbacou
      - icon: linkedin
        href: https://linkedin.com/in/mbacou
      - icon: youtube
        href: https://www.youtube.com/@mbacou/playlists  
  
  sidebar:
    style: docked
    pinned: true
    border: false

  search:
    type: textbox
    show-item-context: true

  announcement:
    dismissable: true
    type: dark
    content: "{{< bi warning >}} This blog is being migrating to [Quarto](https://quarto.org), expect quirks and dead links!"

  page-footer:
    foreground: gray
    background: light

    left: |
      **BACOU, Melanie &copy; 2024** /
      Licensed under [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/).

      All views here are strictly my own and do <u>not</u> reflect that of employers,
      project partners or clients. Refer to each article for citation, code and data reuse.
    right:
      - text: About
        href: about.qmd
      - text: License
        href: license.qmd
      - text: Quarto^®^
        href: https://quarto.org/
      - icon: rss
        href: index.xml      

bibliography: references.bib

format:
  html:
    toc: true
    toc-title: Contents
    toc-location: left
    toc-depth: 3
    toc-expand: true
    link-external-icon: false
    link-external-newwindow: true
    title-block-banner: transparent

    tbl-cap-location: bottom
    fig-cap-location: bottom
    reference-location: margin
    citation-location: document
    citations-hover: true
    footnotes-hover: false

    fig-dpi: 220
    fig-format: png
    fig-width: 7
    fig-height: 4.5

    code-copy: false
    code-overflow: wrap
    highlight-style: solarized

    fontsize: 15px
    include-before-body: assets/scss/navtabs.html
    brand: false
    theme:
      light: assets/scss/theme.scss

    grid:
      body-width: 840px
      sidebar-width: 180px
      margin-width: 180px
      gutter-width: 30px
