project:
  title: mb-labs
  type: website
  execute-dir: file
  output-dir: _site
  render:
    - "**/*.qmd"
    - "**/*.ipynb"
    - "!ejs/**"
  preview:
    port: 5555 

website:
  title: Mel B. mb-labs
  description: Playground for consulting and data science projects
  site-url: https://mbacou.com
  repo-url: https://github.com/mbacou/mb-labs
  favicon: assets/favicon.svg
  image: assets/mb-square.svg
  twitter-card: false
  open-graph: true
  repo-branch: quarto
  repo-actions: [edit, issue]
  back-to-top-navigation: false
  page-navigation: false
  bread-crumbs: false

format:
  mb-article-html:
    logo: assets/mb-square.png
    logo-href: /
    logo-alt: Mel B. mb-labs
    license: CC BY-NC 4.0
    copyright: © Mel B. Labs - a personal blog about statistics and spatial econometrics.
    bibliography: references.bib
    header:
      palette: true
      left: 
        - text: My Blog
          href: index.qmd
          icon: substack
        - text: Portfolio
          href: portfolio.qmd
          icon: briefcase
        - text: Ressources
          href: /posts/tools/
          icon: tools
        - text: Bio / CV
          href: /posts/resume/
          icon: person-circle
      right:
        - icon: github
          href: https://github.com/mbacou/mb-labs
        - icon: telegram
          href: https://t.me/mbacou
        - icon: linkedin
          href: https://linkedin.com/in/mbacou
        - icon: youtube
          href: https://youtube.com/\@mbacou/playlists        
