[format]
line-width = 86
indent-width = 2
indent-style = "space"
line-ending = "auto"
persistent-line-breaks = true
assignment-style = "equal"
exclude = []
default-exclude = true
table = []
default-table = true
skip = ["data.table", "fcase", "graph_from_literal", "."]
